from typing import Any, ClassVar, Self, TypeAliasType, cast, override

from pydantic import BaseModel, ConfigDict, RootModel, create_model

from jsonpatch.registry import OperationRegistry
from jsonpatch.schema import OperationSchema
from jsonpatch.standard import _apply_ops
from jsonpatch.types import _JSON_VALUE_ADAPTER, JSONValue


class _RegistryBoundPatchRoot(RootModel[Any]):
    """
    Internal RootModel base for registry-backed JSON Patch request bodies.

    This base exists to support:

    1) **FastAPI / OpenAPI request bodies** where the incoming JSON is a top-level JSON array.
    2) **Registry-scoped pointer semantics** for :class:`~jsonpatch.types.JSONPointer[...]`.

    ### How context is handled

    ``model_validate(...)`` and ``model_validate_json(...)`` inject the registry's validation context
    (``OperationRegistry._ctx``) if the caller did not supply one. This is critical in web frameworks
    where Pydantic often validates without an explicit context.

    If a caller provides ``context=...``, it is respected as-is (expert override).
    """

    # Choice: This base intentionally uses RootModel[Any].
    # Why: The concrete root type (list[registry.union]) is supplied dynamically
    #      by factories via create_model(). Making this generic would either lie
    #      to the type checker or require pervasive casting with no real benefit.

    model_config = ConfigDict(frozen=True, strict=True)

    __registry__: ClassVar[OperationRegistry]

    @property
    def ops(self) -> list[OperationSchema]:
        # Assumption: subclasses will set root to list[registry.union]
        return cast(list[OperationSchema], self.root)

    @classmethod
    @override
    def model_validate(cls, obj: Any, **kwargs: Any) -> Self:
        # Assumption: callers who do provide context know what they're doing
        #             (or else the PointerBackend context injection silently doesn't happen)
        kwargs.setdefault("context", cls.__registry__._ctx)
        return super().model_validate(obj, **kwargs)

    @classmethod
    @override
    def model_validate_json(
        cls, json_data: str | bytes | bytearray, **kwargs: Any
    ) -> Self:
        # Assumption: callers who do provide context know what they're doing
        #             (or else the PointerBackend context injection silently doesn't happen)
        kwargs.setdefault("context", cls.__registry__._ctx)
        return super().model_validate_json(json_data, **kwargs)


class _BasePatchModel(_RegistryBoundPatchRoot):
    """
    Patch model for **model-aware patching** (patch a Pydantic model instance).

    Subclasses of this type are generated by :class:`JsonPatchFor` and represent a JSON Patch
    whose operations are validated against an :class:`~jsonpatch.registry.OperationRegistry`.

    The JSON representation is a top-level list of operations (a standard JSON Patch document).

    ### What you get

    - Strong validation of operations (discriminated union on ``op``).
    - Registry-scoped JSONPointer handling (custom pointer backends supported).
    - A convenience :meth:`apply` method that patches a Pydantic model instance and returns a
      new validated instance of the target model.

    ### Contract of :meth:`apply`

    - Accepts a Pydantic ``BaseModel`` instance.
    - Applies operations to the model's ``model_dump()`` representation using the shared patch engine.
    - Validates the patched output back into the target model via ``model_validate``.
    - The original model instance is not mutated in-place.
    - If the patch contains no operations, returns the original target unchanged.
    """

    __target_model__: ClassVar[type[BaseModel]]

    def apply(self, target: BaseModel) -> BaseModel:
        if not isinstance(target, BaseModel):
            raise TypeError(
                f"{self.__class__.__name__}.apply() expects a Pydantic BaseModel instance, "
                f"got {type(target).__name__}"
            )
        if not self.ops:
            return target
        data = target.model_dump()
        patched = _apply_ops(self.ops, data)
        return self.__target_model__.model_validate(patched)


class JsonPatchFor[ModelT: BaseModel]:
    """
    Factory for creating **typed JSON Patch models** for a specific Pydantic model.

    This is intended for endpoints and internal APIs where:

    - the request body is a standard JSON Patch document (a JSON array of ops),
    - you want OpenAPI to show each operation as a first-class discriminated type,
    - and you want an ergonomic ``.apply(model_instance)`` method.

    ### Usage

    Standard RFC 6902 operations::

        UserPatch = JsonPatchFor[User]
        patch = UserPatch.model_validate([
            {"op": "replace", "path": "/name", "value": "Angela"}
        ])
        updated_user = patch.apply(user)

    Custom operations / custom pointer backend (registry-scoped)::

        registry = OperationRegistry.with_standard(IncrementOp, pointer_cls=MyPointer)
        UserPatch = JsonPatchFor[(User, registry)]

    ### Parameters

    ``JsonPatchFor[...]`` accepts either:

    - ``JsonPatchFor[MyModel]`` — uses the standard RFC 6902 registry
    - ``JsonPatchFor[(MyModel, registry)]`` — uses an explicit :class:`OperationRegistry`

    The returned type is a dynamically generated :class:`pydantic.RootModel` subclass whose
    JSON shape is a top-level list.
    """

    def __class_getitem__(
        cls, param: type[BaseModel] | tuple[type[BaseModel], OperationRegistry]
    ) -> type[_BasePatchModel]:
        if isinstance(param, tuple):
            if len(param) != 2:
                raise TypeError(
                    "JsonPatchFor[(Model, registry)] expects exactly two items"
                )
            model, registry = param
        else:
            model, registry = param, OperationRegistry.standard()

        # Verify that model is a BaseModel subclass. Must verify that model is a type first or else issubclass complains.
        if not isinstance(model, type) or not issubclass(model, BaseModel):  # type: ignore[redundant-expr]
            raise TypeError(
                f"JsonPatchFor[...] expects a Pydantic BaseModel, got {model!r}"
            )

        if not isinstance(registry, OperationRegistry):
            raise TypeError(
                "JsonPatchFor[(Model, registry)] second argument must be an OperationRegistry, "
                f"got {type(registry).__name__}"
            )

        return cls._create_patch_model(model, registry)

    @staticmethod
    def _create_patch_model(
        model: type[BaseModel],
        registry: OperationRegistry,
    ) -> type[_BasePatchModel]:
        """Dynamically create the Pydantic model class."""
        registry_union: TypeAliasType = registry.union  # runtime discriminated union

        PatchModel = create_model(
            f"{model.__name__}Patch",
            __base__=_BasePatchModel,
            root=(list[registry_union], ...),  # type: ignore[valid-type]
        )

        PatchModel.__target_model__ = model
        PatchModel.__registry__ = registry
        return PatchModel


class _BasePatchBody(_RegistryBoundPatchRoot):
    """
    Patch model for **typed operations applied to an untyped JSON document**.

    This is the “FastAPI PATCH over plain JSON” mode:

    - operations are validated and typed (including custom/domain ops),
    - the document being patched is a plain JSON value (dict/list/primitives),
    - the patched output is returned as JSON without any model-aware revalidation.

    This is useful when your persistence layer stores schemaless JSON (e.g., JSONB / document stores)
    but you still want a strongly controlled mutation interface.

    ### Contract of :meth:`apply`

    - Applies operations using the shared patch engine (``_apply_ops``).
    - If ``validate_doc=True``, validates that the input document is a strict JSON value before applying the patch.
    - Copying vs in-place behavior is controlled by ``inplace``:
        - ``inplace=False`` (default): the engine deep-copies the input document first, then applies operations
          (which may perform in-place edits) to that copy; the original input object is not modified.
        - ``inplace=True``: operations are applied to the provided object. If an operation fails mid-patch,
          earlier operations will have already mutated the document (no rollback).

    Operation implementations are allowed to mutate the document object they receive and must return the updated
    document (which may be the same object).
    """

    def apply(
        self, doc: JSONValue, *, validate_doc: bool = False, inplace: bool = False
    ) -> JSONValue:
        if validate_doc:
            _JSON_VALUE_ADAPTER.validate_python(doc, strict=True)
        return _apply_ops(self.ops, doc, inplace=inplace)


def make_json_patch_body(
    registry: OperationRegistry | None = None,
    *,
    name: str | None = None,
) -> type[_BasePatchBody]:
    """
    Create a Pydantic model type suitable for a **FastAPI request body** representing a JSON Patch.

    The returned model is a dynamically generated :class:`pydantic.RootModel` subclass whose JSON
    representation is a top-level array of operations (i.e., a standard JSON Patch document).

    This is the recommended API when you want:

    - **typed operations** (including custom ops) with OpenAPI support
    - a **plain JSON document** as the patch target (dict/list/primitives)
    - an ergonomic ``patch.apply(doc)`` method in your endpoint

    ### Usage (typed ops, untyped doc)

    ::

        registry = OperationRegistry.with_standard(IncrementOp)
        ConfigPatchBody = make_json_patch_body(registry, name="ConfigPatch")

        @app.patch("/configs/{config_id}")
        def patch_config(config_id: str, patch: ConfigPatchBody):
            doc = load_config(config_id)       # plain dict / JSON
            updated = patch.apply(doc)         # typed ops, untyped document
            save_config(config_id, updated)
            return updated

    ### Parameters

    registry:
        The :class:`~jsonpatch.registry.OperationRegistry` used to validate and parse operations.
        If omitted, the standard RFC 6902 registry is used.

    name:
        Optional name of the generated model class. Naming the class can improve OpenAPI output
        (schemas become easier to read and reuse).

    ### Notes

    - The registry's validation context is automatically injected during parsing so JSONPointer fields
      can use the registry's configured pointer backend.
    - You should typically create these model types at import time (module scope) so FastAPI/OpenAPI
      sees a stable schema.
    """

    registry = registry or OperationRegistry.standard()
    registry_union: TypeAliasType = registry.union  # runtime discriminated union

    PatchBody = create_model(
        name or "JsonPatchBody",
        __base__=_BasePatchBody,
        root=(list[registry_union], ...),  # type: ignore[valid-type]
    )

    PatchBody.__registry__ = registry
    return PatchBody
